[package]
name = "pyimportparse"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = "2.8"
pest_derive = "2.8"
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
itertools = "0.14.0"
parameterized = "2.0.0"
pretty_assertions = "1.4.1"
pyimports = "0.6.7"
serde_json = "1.0.140"
walkdir = "2.5.0"

