version: "3"

tasks:
  test:
    cmds:
      - cargo test --all-features

  lint:
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings
      - cargo fmt --check

  clippy.fix:
    cmds:
      - cargo clippy --all-targets --all-features --fix --allow-staged

  fmt:
    cmds:
      - cargo fmt

  check:
    cmds:
      - task: test
      - task: lint
